### ISSUE TITLE
Forms for login, logout, and Talk submission are misaligned 

### ISSUE THREAD

**Issue by hbutau** [PyZim/indaba#1]
* indaba version:
* Python version: 3.5
* Operating System: Ubuntu

### Description

The text when filling out the talk submission form  is not visible. The fields are just too small. the same goes for the authentucation horizontal forms

**Comment by ronnzw** [comment]
i wanted to contribute but everything is confusing.l'm now trying to work how i can see what has been done so far.I have cloned the repo but i cn't even run the server.l will let you know when l strike the break through.

**Comment by ronnzw** [comment]
Finally managed to run it but l fail to install psycopg2. If you can l assist i would gladly appreciate it.i am now working on it.l will probably use the sqlite database and you can easily convert it into a postgres database.
